### ISSUE TITLE
npm test  and nom run-script watch are all borken 

### ISSUE THREAD

**Issue by ypwu1** [backstopmedia/bleeding-edge-sample-app#49]
Enviroment: Mac OSX yosemite
Node Version: v0.10.33
Npm Version: 2.1.9

run npm test, got following error:
[ReactifyError: /Users/ypwu1/dev/github/bleeding-edge-sample-app/test/client/shared_examples/interval_mixin_shared_examples.js: Lower case component names (componentClass) are no longer supported in JSX: See http://fb.me/react-jsx-lower-case]
  name: 'ReactifyError',

run npm run-script watch
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "watch"
npm ERR! node v0.10.33
npm ERR! npm  v2.1.9

npm ERR! missing script: watch
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ypwu1/dev/github/bleeding-edge-sample-app/npm-debug.log
Yuans-MacBook-Pro-2:bleeding-edge-sample-app ypwu1$

**Comment by stabenfeldt** [comment]
When is the errors in the code expected to be fixed? Is the book still in progress?

**Comment by eiriklv** [comment]
hi @winkler1!
also: + 1..

**Comment by karlmikko** [comment]
Thanks all for notifying us of these issues - work was being done to move the example project to React 0.12 however some of the dependencies were not passing tests with React 0.12 and these bubbled up to our project. Subsequently these dependencies have had some major breaking API changes, making it difficult to migrate the sample app to React 0.12 as some of the code examples in the book would not reflect the code in the sample app. 

The sample app has now been rolled back to the last working version with React 0.11.
